// AUTO-GENERATED BY ADESSO AI AGENT — DO NOT EDIT MANUALLY
package com.sivalabs.bookstore.mcp;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/mcp")
@CrossOrigin(origins = "*")
public class McpController {

    private final McpService mcpService;
    private final ObjectMapper mapper = new ObjectMapper()
        .setSerializationInclusion(JsonInclude.Include.NON_NULL);

    public McpController(McpService mcpService) {
        this.mcpService = mcpService;
    }

    @PostMapping(
        consumes = MediaType.APPLICATION_JSON_VALUE,
        produces = MediaType.APPLICATION_JSON_VALUE
    )
    public ResponseEntity<Map<String, Object>> handle(@RequestBody Map<String, Object> req) {
        String method = (String) req.get("method");
        Object id = req.getOrDefault("id", 1);

        return switch (method) {
            case "initialize" -> ok(id, Map.of(
                "protocolVersion", "2024-11-05",
                "capabilities", Map.of("tools", Map.of()),
                "serverInfo", Map.of(
                    "name", "bookstore-mcp",
                    "version", "1.0.0",
                    "description", "Spring Modulith Bookstore — agentenfähige Modul-APIs"
                )
            ));
            case "tools/list" -> ok(id, Map.of("tools", mcpService.listTools()));
            case "tools/call" -> {
                @SuppressWarnings("unchecked")
                Map<String, Object> params = (Map<String, Object>) req.getOrDefault("params", Map.of());
                String toolName = (String) params.get("name");
                @SuppressWarnings("unchecked")
                Map<String, Object> args = (Map<String, Object>) params.getOrDefault("arguments", Map.of());
                try {
                    Object result = mcpService.callTool(toolName, args);
                    yield ok(id, Map.of("content", List.of(
                        Map.of("type", "text", "text", mapper.writeValueAsString(result))
                    )));
                } catch (Exception e) {
                    yield ResponseEntity.ok(Map.of(
                        "jsonrpc", "2.0", "id", id,
                        "error", Map.of("code", -32000, "message", e.getMessage())
                    ));
                }
            }
            default -> ResponseEntity.ok(Map.of(
                "jsonrpc", "2.0", "id", id,
                "error", Map.of("code", -32601, "message", "Method not found: " + method)
            ));
        };
    }

    private ResponseEntity<Map<String, Object>> ok(Object id, Object result) {
        return ResponseEntity.ok(Map.of("jsonrpc", "2.0", "id", id, "result", result));
    }
}
