// AUTO-GENERATED BY ADESSO AI AGENT — AGSDLC-11
// MCP JSON-RPC 2.0 Dispatcher
package com.sivalabs.bookstore.mcp;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * MCP-Controller: Implementiert den Model Context Protocol (MCP) JSON-RPC 2.0 Dispatcher.
 *
 * <h3>Endpunkte:</h3>
 * <ul>
 *   <li>{@code POST /mcp} — JSON-RPC 2.0 Dispatcher: {@code initialize}, {@code tools/list},
 *       {@code tools/call}</li>
 * </ul>
 *
 * <h3>JSON-RPC 2.0 Response-Format:</h3>
 * <pre>
 * Erfolg: {"jsonrpc":"2.0","id":N,"result":{...}}
 * Fehler: {"jsonrpc":"2.0","id":N,"error":{"code":-32000,"message":"..."}}
 * </pre>
 *
 * <h3>Sicherheit:</h3>
 * {@code /mcp/**} ist durch {@code McpSecurityConfig} (@Order(1)) mit CSRF-disabled und
 * permitAll() abgesichert. CORS ist für MCP-Client-Kompatibilität auf {@code *} gesetzt
 * (Demo-Scope). CSRF ist zusätzlich in {@code WebSecurityConfig} via
 * {@code ignoringRequestMatchers("/mcp", "/mcp/**")} deaktiviert.
 */
@SuppressWarnings({"NullAway", "NullAway.Init"})
@RestController
@RequestMapping("/mcp")
@CrossOrigin(origins = "*")
public class McpController {

    private static final String JSONRPC_VERSION = "2.0";
    private static final String SERVER_NAME = "bookstore-mcp";
    private static final String SERVER_VERSION = "1.0.0";
    private static final String PROTOCOL_VERSION = "2024-11-05";

    private final McpService mcpService;

    /** ObjectMapper für JSON-Serialisierung von Tool-Ergebnissen. */
    private final ObjectMapper mapper = new ObjectMapper();

    public McpController(McpService mcpService) {
        this.mcpService = mcpService;
    }

    // ── JSON-RPC 2.0 Dispatcher ────────────────────────────────────────────────

    /**
     * Haupt-Dispatcher für MCP JSON-RPC 2.0 Requests.
     *
     * <p>Unterstützte Methoden:
     * <ul>
     *   <li>{@code initialize} — Handshake: Protokollversion, Capabilities, ServerInfo</li>
     *   <li>{@code tools/list} — Alle verfügbaren MCP-Tools mit Input-Schema</li>
     *   <li>{@code tools/call} — Tool-Ausführung, Ergebnis als MCP Content-Block</li>
     * </ul>
     *
     * <p>JSON-RPC Notifications (kein {@code id}-Feld) werden mit HTTP 204 No Content
     * beantwortet.
     *
     * @param req JSON-RPC 2.0 Request-Objekt
     * @return JSON-RPC 2.0 Response (Erfolg oder Fehler)
     */
    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<?> handle(@RequestBody Map<String, Object> req) {
        // JSON-RPC 2.0 Notifications (kein 'id') → keine Antwort erforderlich
        if (!req.containsKey("id")) {
            return ResponseEntity.noContent().build();
        }

        Object id = req.get("id");
        String method = req.containsKey("method") ? (String) req.get("method") : "";

        return switch (method) {

            // ── initialize ───────────────────────────────────────────────────
            case "initialize" ->
                ok(
                        id,
                        Map.of(
                                "protocolVersion", PROTOCOL_VERSION,
                                "capabilities", Map.of("tools", Map.of()),
                                "serverInfo",
                                        Map.of(
                                                "name", SERVER_NAME,
                                                "version", SERVER_VERSION,
                                                "description",
                                                        "Spring Modulith Bookstore — MCP-Layer für Katalog, Bestellungen und Inventar")));

            // ── tools/list ───────────────────────────────────────────────────
            case "tools/list" -> ok(id, Map.of("tools", mcpService.listTools()));

            // ── tools/call ───────────────────────────────────────────────────
            case "tools/call" -> {
                @SuppressWarnings("unchecked")
                Map<String, Object> params =
                        req.containsKey("params") ? (Map<String, Object>) req.get("params") : Map.of();

                String toolName = params.containsKey("name") ? (String) params.get("name") : null;
                if (toolName == null || toolName.isBlank()) {
                    yield mcpError(id, -32602, "Ungültige Parameter: 'name' fehlt im tools/call-Request");
                }

                @SuppressWarnings("unchecked")
                Map<String, Object> args =
                        params.containsKey("arguments") ? (Map<String, Object>) params.get("arguments") : Map.of();

                try {
                    Object result = mcpService.callTool(toolName, args);
                    String resultJson = mapper.writeValueAsString(result);

                    Map<String, Object> contentBlock = new HashMap<>();
                    contentBlock.put("type", "text");
                    contentBlock.put("text", resultJson);

                    yield ok(id, Map.of("content", List.of(contentBlock)));

                } catch (IllegalArgumentException e) {
                    // Tool-Fehler: unbekanntes Tool, fehlende Parameter, Ressource nicht gefunden
                    yield mcpError(id, -32602, e.getMessage());
                } catch (Exception e) {
                    // Allgemeiner Server-Fehler: DB-Fehler, InvalidOrderException, etc.
                    String msg = e.getMessage() != null
                            ? e.getMessage()
                            : e.getClass().getSimpleName();
                    yield mcpError(id, -32000, msg);
                }
            }

            // ── Unbekannte Methode ───────────────────────────────────────────
            default -> mcpError(id, -32601, "Method not found: '" + method + "'");
        };
    }

    // ── Hilfsmethoden ─────────────────────────────────────────────────────────

    /**
     * Erstellt eine JSON-RPC 2.0 Erfolgs-Response.
     *
     * @param id     Request-ID (wird 1:1 zurückgespiegelt)
     * @param result Result-Objekt (wird als {@code result}-Feld gesetzt)
     */
    private ResponseEntity<Map<String, Object>> ok(Object id, Object result) {
        Map<String, Object> response = new HashMap<>();
        response.put("jsonrpc", JSONRPC_VERSION);
        response.put("id", id);
        response.put("result", result);
        return ResponseEntity.ok(response);
    }

    /**
     * Erstellt eine JSON-RPC 2.0 Fehler-Response.
     *
     * @param id      Request-ID
     * @param code    JSON-RPC Error-Code:
     *                -32601 Method Not Found,
     *                -32602 Invalid Params,
     *                -32000 Server Error
     * @param message Menschenlesbare Fehlermeldung
     */
    private ResponseEntity<Map<String, Object>> mcpError(Object id, int code, String message) {
        Map<String, Object> errorDetail = new HashMap<>();
        errorDetail.put("code", code);
        errorDetail.put("message", message != null ? message : "Unbekannter Fehler");

        Map<String, Object> response = new HashMap<>();
        response.put("jsonrpc", JSONRPC_VERSION);
        response.put("id", id);
        response.put("error", errorDetail);
        return ResponseEntity.ok(response);
    }
}
