// AUTO-GENERATED BY ADESSO AI AGENT — AGSDLC-11
// Modul-Grenzen als agentenfähige Fähigkeiten: Katalog · Bestellungen · Inventar
package com.sivalabs.bookstore.mcp;

import com.sivalabs.bookstore.catalog.ProductApi;
import com.sivalabs.bookstore.inventory.InventoryApi;
import com.sivalabs.bookstore.inventory.InventoryStockView;
import com.sivalabs.bookstore.orders.OrdersApi;
import com.sivalabs.bookstore.orders.domain.models.CreateOrderCmd;
import com.sivalabs.bookstore.orders.domain.models.Customer;
import com.sivalabs.bookstore.orders.domain.models.OrderItem;
import com.sivalabs.bookstore.orders.domain.models.OrderStatus;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Service;

/**
 * MCP-Service: Implementiert alle 8 Tool-Methoden des Model Context Protocol Layers.
 *
 * <p>Modulgrenz-Strategie (Spring Modulith konform):
 *
 * <ul>
 *   <li><b>catalog</b>: {@link ProductApi} — öffentliche Fassade für alle Katalog-Operationen
 *       (list_products, get_product, Produkt-Lookup für create_order)
 *   <li><b>orders</b>: {@link OrdersApi} — öffentliche Fassade für alle Bestell-Operationen
 *       (create_order, list_orders, get_order, update_order_status)
 *   <li><b>inventory</b>: {@link InventoryApi} — öffentliche Fassade für Inventar-Abfragen
 *       (get_stock_level, list_low_stock)
 * </ul>
 *
 * <p>Kein direkter Zugriff auf interne Service-Klassen ({@code ProductService},
 * {@code OrderService}, {@code InventoryService}) — ausschließlich öffentliche API-Fassaden.
 * Alle Methoden liefern echte Daten — keine Stubs oder Mocks.
 */
@SuppressWarnings({"NullAway", "NullAway.Init"})
@Service
public class McpService {

    private final ProductApi productApi;
    private final OrdersApi ordersApi;
    private final InventoryApi inventoryApi;

    public McpService(ProductApi productApi, OrdersApi ordersApi, InventoryApi inventoryApi) {
        this.productApi = productApi;
        this.ordersApi = ordersApi;
        this.inventoryApi = inventoryApi;
    }

    // ── Tool-Definitionen (MCP tools/list) ────────────────────────────────────

    /**
     * Liefert die Liste aller registrierten MCP-Tools mit Name, Beschreibung und Input-Schema.
     * Wird vom MCP-Controller für die JSON-RPC-Methode {@code tools/list} genutzt.
     */
    public List<Map<String, Object>> listTools() {
        return List.of(

                // ── KATALOG-MODUL ────────────────────────────────────────────────
                tool(
                        "list_products",
                        "[Katalog] Listet alle aktiven Bücher/Produkte seitenweise auf (Seitengröße: 10, alphabetisch nach Name).",
                        Map.of(
                                "page",
                                Map.of(
                                        "type", "integer",
                                        "description", "Seitennummer (ab 1, Standard: 1)"))),
                tool(
                        "get_product",
                        "[Katalog] Gibt vollständige Produktdetails (Name, Preis, Beschreibung) für einen Produktcode zurück. Nur aktive Produkte.",
                        Map.of(
                                "code",
                                Map.of(
                                        "type", "string",
                                        "description", "Eindeutiger Produktcode, z.B. 'P100'"))),

                // ── BESTELLUNGEN-MODUL ───────────────────────────────────────────
                tool(
                        "list_orders",
                        "[Bestellungen] Listet alle Bestellungen admin-seitig auf (sortiert nach createdAt desc). Optionaler Status-Filter.",
                        Map.of(
                                "page",
                                        Map.of(
                                                "type", "integer",
                                                "description", "Seitennummer (ab 1, Standard: 1)"),
                                "status",
                                        Map.of(
                                                "type",
                                                "string",
                                                "description",
                                                "Optional: NEW | IN_PROCESS | DELIVERED | CANCELLED | ERROR"))),
                tool(
                        "get_order",
                        "[Bestellungen] Gibt alle Details einer Bestellung anhand der Bestellnummer zurück (Admin-Ansicht).",
                        Map.of(
                                "orderNumber",
                                Map.of(
                                        "type", "string",
                                        "description", "Bestellnummer, z.B. 'ORD-2025-12345'"))),
                tool(
                        "create_order",
                        "[Bestellungen] Legt eine neue Bestellung an und löst OrderCreatedEvent aus (→ Inventar-Reduktion, RabbitMQ-Notification).",
                        Map.of(
                                "customerName",
                                        Map.of("type", "string", "description", "Vollständiger Name des Kunden"),
                                "customerEmail", Map.of("type", "string", "description", "E-Mail-Adresse des Kunden"),
                                "customerPhone", Map.of("type", "string", "description", "Telefonnummer des Kunden"),
                                "deliveryAddress",
                                        Map.of("type", "string", "description", "Vollständige Lieferadresse"),
                                "productCode",
                                        Map.of(
                                                "type",
                                                "string",
                                                "description",
                                                "Produktcode aus dem Katalog, z.B. 'P100'"),
                                "quantity", Map.of("type", "integer", "description", "Bestellmenge (min. 1)"))),
                tool(
                        "update_order_status",
                        "[Bestellungen] Ändert den Status einer Bestellung. Erlaubte Übergänge: NEW→IN_PROCESS|CANCELLED, IN_PROCESS→DELIVERED|CANCELLED.",
                        Map.of(
                                "orderNumber",
                                        Map.of(
                                                "type",
                                                "string",
                                                "description",
                                                "Bestellnummer der zu ändernden Bestellung"),
                                "status",
                                        Map.of(
                                                "type",
                                                "string",
                                                "description",
                                                "Neuer Status: IN_PROCESS | DELIVERED | CANCELLED"))),

                // ── INVENTAR-MODUL ───────────────────────────────────────────────
                tool(
                        "get_stock_level",
                        "[Inventar] Gibt den aktuellen Lagerbestand für einen Produktcode zurück. Gibt 0 zurück wenn nicht erfasst.",
                        Map.of(
                                "productCode",
                                Map.of(
                                        "type", "string",
                                        "description", "Produktcode für Lagerbestands-Abfrage"))),
                tool(
                        "list_low_stock",
                        "[Inventar] Listet alle Produkte mit Lagerbestand ≤ threshold auf. Standard-Schwellwert: 10.",
                        Map.of(
                                "threshold",
                                Map.of(
                                        "type", "integer",
                                        "description", "Schwellwert für 'niedrigen Bestand' (Standard: 10)"))));
    }

    // ── Tool-Ausführung (MCP tools/call) ──────────────────────────────────────

    /**
     * Führt ein benanntes MCP-Tool aus und gibt das Ergebnis als strukturiertes Objekt zurück.
     *
     * @param name Tool-Name gemäß listTools()
     * @param args Tool-Argumente als Key-Value-Map
     * @return Strukturiertes Ergebnis-Objekt (wird vom Controller zu JSON serialisiert)
     * @throws IllegalArgumentException bei unbekanntem Tool-Name oder fehlenden Pflichtargumenten
     */
    public Object callTool(String name, Map<String, Object> args) {
        return switch (name) {

            // ── KATALOG: list_products ───────────────────────────────────────
            case "list_products" -> {
                int page = args.containsKey("page") ? ((Number) args.get("page")).intValue() : 1;
                var result = productApi.getProducts(page);
                yield Map.of(
                        "totalElements", result.totalElements(),
                        "totalPages", result.totalPages(),
                        "pageNumber", result.pageNumber(),
                        "data",
                                result.data().stream()
                                        .map(p -> {
                                            Map<String, Object> m = new HashMap<>();
                                            m.put("code", p.code());
                                            m.put("name", p.name());
                                            m.put("price", p.price());
                                            // description und imageUrl sind optional — null-safe
                                            if (p.description() != null) m.put("description", p.description());
                                            if (p.imageUrl() != null) m.put("imageUrl", p.imageUrl());
                                            return m;
                                        })
                                        .toList());
            }

            // ── KATALOG: get_product ─────────────────────────────────────────
            case "get_product" -> {
                String code = (String) args.get("code");
                if (code == null || code.isBlank()) {
                    throw new IllegalArgumentException("Pflichtparameter 'code' fehlt oder ist leer");
                }
                yield productApi
                        .getByCode(code)
                        .map(p -> {
                            Map<String, Object> m = new HashMap<>();
                            m.put("code", p.code());
                            m.put("name", p.name());
                            m.put("price", p.price());
                            m.put("description", p.description() != null ? p.description() : "");
                            return (Object) m;
                        })
                        .orElseThrow(() -> new IllegalArgumentException("Produkt nicht gefunden: " + code));
            }

            // ── BESTELLUNGEN: list_orders ────────────────────────────────────
            case "list_orders" -> {
                int page = args.containsKey("page") ? ((Number) args.get("page")).intValue() : 1;
                // Status-Filter defensiv parsen — ungültige Werte werden ignoriert
                OrderStatus status = null;
                if (args.containsKey("status")
                        && args.get("status") instanceof String rawStatus
                        && !rawStatus.isBlank()) {
                    try {
                        status = OrderStatus.valueOf(rawStatus.trim().toUpperCase());
                    } catch (IllegalArgumentException ignored) {
                        // Ungültiger Status-Wert → kein Filter (alle Bestellungen)
                    }
                }
                var result = ordersApi.getOrdersAdmin(page, status);
                yield Map.of(
                        "totalElements", result.totalElements(),
                        "totalPages", result.totalPages(),
                        "pageNumber", result.pageNumber(),
                        "data",
                                result.data().stream()
                                        .map(o -> {
                                            Map<String, Object> m = new HashMap<>();
                                            m.put("orderNumber", o.orderNumber());
                                            m.put("status", o.status().name());
                                            m.put("customerName", o.customerName());
                                            m.put("createdAt", o.createdAt().toString());
                                            return m;
                                        })
                                        .toList());
            }

            // ── BESTELLUNGEN: get_order ──────────────────────────────────────
            case "get_order" -> {
                String orderNumber = (String) args.get("orderNumber");
                if (orderNumber == null || orderNumber.isBlank()) {
                    throw new IllegalArgumentException("Pflichtparameter 'orderNumber' fehlt oder ist leer");
                }
                yield ordersApi
                        .findOrderAdmin(orderNumber)
                        .map(o -> {
                            Map<String, Object> m = new HashMap<>();
                            m.put("orderNumber", o.orderNumber());
                            m.put("status", o.status().name());
                            m.put("customerName", o.customer().name());
                            m.put("customerEmail", o.customer().email());
                            m.put("customerPhone", o.customer().phone());
                            m.put("deliveryAddress", o.deliveryAddress());
                            m.put("productCode", o.item().code());
                            m.put("productName", o.item().name());
                            m.put("quantity", o.item().quantity());
                            m.put("price", o.item().price());
                            m.put("totalAmount", o.getTotalAmount());
                            m.put("createdAt", o.createdAt().toString());
                            return (Object) m;
                        })
                        .orElseThrow(() -> new IllegalArgumentException("Bestellung nicht gefunden: " + orderNumber));
            }

            // ── BESTELLUNGEN: create_order ───────────────────────────────────
            case "create_order" -> {
                String productCode = (String) args.get("productCode");
                if (productCode == null || productCode.isBlank()) {
                    throw new IllegalArgumentException("Pflichtparameter 'productCode' fehlt");
                }
                int qty = args.containsKey("quantity") ? ((Number) args.get("quantity")).intValue() : 0;
                if (qty < 1) {
                    throw new IllegalArgumentException("'quantity' muss mindestens 1 sein, war: " + qty);
                }

                // Produkt-Lookup via ProductApi (öffentliche Modul-Fassade) → Preis + Name
                var product = productApi
                        .getByCode(productCode)
                        .orElseThrow(() -> new IllegalArgumentException("Produkt nicht gefunden: " + productCode));

                var customer =
                        new Customer((String) args.get("customerName"), (String) args.get("customerEmail"), (String)
                                args.get("customerPhone"));

                // OrderItem.price = Stückpreis (OrderDto.getTotalAmount() = price × quantity)
                var item = new OrderItem(
                        productCode,
                        product.name(),
                        product.price(), // Stückpreis — getTotalAmount() multipliziert qty
                        qty);

                var cmd = new CreateOrderCmd(null, customer, (String) args.get("deliveryAddress"), item);
                var result = ordersApi.createOrder(cmd);
                yield Map.of("orderNumber", result.orderNumber(), "status", "NEW");
            }

            // ── BESTELLUNGEN: update_order_status ───────────────────────────
            case "update_order_status" -> {
                String orderNumber = (String) args.get("orderNumber");
                String rawStatus = (String) args.get("status");
                if (orderNumber == null || orderNumber.isBlank()) {
                    throw new IllegalArgumentException("Pflichtparameter 'orderNumber' fehlt");
                }
                if (rawStatus == null || rawStatus.isBlank()) {
                    throw new IllegalArgumentException("Pflichtparameter 'status' fehlt");
                }
                OrderStatus newStatus;
                try {
                    newStatus = OrderStatus.valueOf(rawStatus.trim().toUpperCase());
                } catch (IllegalArgumentException e) {
                    throw new IllegalArgumentException(
                            "Ungültiger Status-Wert: '" + rawStatus + "'. Erlaubt: IN_PROCESS, DELIVERED, CANCELLED");
                }
                // updateOrderStatus wirft InvalidOrderException bei unerlaubtem Übergang
                ordersApi.updateOrderStatus(orderNumber, newStatus);
                yield Map.of("orderNumber", orderNumber, "newStatus", newStatus.name(), "updated", true);
            }

            // ── INVENTAR: get_stock_level ────────────────────────────────────
            case "get_stock_level" -> {
                String productCode = (String) args.get("productCode");
                if (productCode == null || productCode.isBlank()) {
                    throw new IllegalArgumentException("Pflichtparameter 'productCode' fehlt");
                }
                Long qty = inventoryApi.getStockLevel(productCode);
                yield Map.of("productCode", productCode, "quantity", qty != null ? qty : 0L);
            }

            // ── INVENTAR: list_low_stock ─────────────────────────────────────
            case "list_low_stock" -> {
                int threshold = args.containsKey("threshold") ? ((Number) args.get("threshold")).intValue() : 10;
                // getAllInventoryFirstPage(): erste Seite des Inventars (PAGE_SIZE=10)
                // Bei kleinem Demo-Datenbestand ausreichend; Produktivierung: dedizierter DB-Query
                List<InventoryStockView> allInventory = inventoryApi.getAllInventoryFirstPage();
                var lowStockItems = allInventory.stream()
                        .filter(i -> i.quantity() <= threshold)
                        .map(i -> Map.of(
                                "productCode", (Object) i.productCode(),
                                "quantity", (Object) i.quantity()))
                        .toList();
                yield Map.of(
                        "threshold", threshold,
                        "count", lowStockItems.size(),
                        "items", lowStockItems);
            }

            // ── Unbekanntes Tool ─────────────────────────────────────────────
            default -> throw new IllegalArgumentException("Unbekanntes Tool: '" + name + "'");
        };
    }

    // ── Hilfsmethoden ─────────────────────────────────────────────────────────

    /**
     * Erstellt eine MCP-Tool-Definition für listTools().
     *
     * @param name  Tool-Name (snake_case)
     * @param desc  Kurzbeschreibung für den MCP-Client
     * @param props Input-Schema-Properties als Map
     * @return Tool-Definition-Map im MCP-Format
     */
    private Map<String, Object> tool(String name, String desc, Map<String, Object> props) {
        Map<String, Object> schema = new HashMap<>();
        schema.put("type", "object");
        schema.put("properties", props);
        return Map.of(
                "name", name,
                "description", desc,
                "inputSchema", schema);
    }
}
